### ISSUE TITLE
How to use in react js

### ISSUE THREAD

**Issue by oyhan** [uxitten/jetemit#4]
Hi.
I want to use in a reactjs app . 
Briefly I emitted an event in a component and subscribed for it in another component constructor  but
it does not receive anything . 
Something special needs to work?

**Comment by behnammodi** [comment]
Suppose  we have two component A and B

in component A

```javascript
componentDidMount(){
  on('TIME',time=>{
    this.setState({time});
  });
}
```

and in component B

```javascript
componentDidMount(){
  emit('TIME', '2018-12-01 12:30');
}
```
is it was clear?
